import unified = require('unified')
import document = require('rehype-document')

unified().use(document)
unified().use(document, {title: ''})
unified().use(document, {language: ''})
unified().use(document, {responsive: false})
unified().use(document, {doctype: ''})
unified().use(document, {style: ''})
unified().use(document, {style: ['']})
unified().use(document, {css: ''})
unified().use(document, {css: ['']})
unified().use(document, {meta: {name: '', content: ''}})
unified().use(document, {meta: [{name: '', content: ''}]})
unified().use(document, {link: {name: '', content: ''}})
unified().use(document, {link: [{name: '', content: ''}]})
unified().use(document, {script: ''})
unified().use(document, {script: ['']})
unified().use(document, {js: ''})
unified().use(document, {js: ['']})
